package app.meethalfway.meetings.domain.model;

/**
 * Externalized, city-agnostic engine configuration read by the optimization
 * logic (Requirements 5.4, 11.5). All city-specific and tunable values live here
 * so no Medellín-specific number is embedded in the algorithm; the engine reads
 * these values, it never hard-codes them.
 *
 * <p>This is the framework-free domain snapshot. The framework-facing binding
 * ({@code app.meethalfway.config.MeetHalfwayProperties.Engine}) is mapped into this
 * record at the composition root, keeping the domain independent of Spring.
 *
 * <p>Note the deliberate omission: the 15% {@code Efficiency_Tolerance} is
 * <em>not</em> a field here. Requirement 4.3 mandates it be a fixed constant, so
 * it lives as {@code app.meethalfway.meetings.domain.model.DomainConstants.EFFICIENCY_TOLERANCE}
 * and can never become a user control.
 *
 * <p>Invariants enforced at construction:
 * <ul>
 *   <li>{@code serviceBounds} and {@code outlierRule} are non-null;</li>
 *   <li>{@code gridDensityN >= 1} (Grid_Search must generate at least one point);</li>
 *   <li>{@code maxSearchRadiusMeters} is finite and strictly positive;</li>
 *   <li>{@code epsilonMinutes} is finite and strictly positive.</li>
 * </ul>
 *
 * @param serviceBounds         the served-region bounding box (Requirement 1.7)
 * @param gridDensityN          number of candidate points generated by Grid_Search
 *                              (Open Question: N); must be {@code >= 1}
 * @param maxSearchRadiusMeters maximum grid extent in meters (Open Question: max
 *                              radius); must be finite and strictly positive
 * @param outlierRule           the config-driven outlier detection rule (Requirement 7.1)
 * @param epsilonMinutes        the float-comparison tie tolerance ε in minutes
 *                              (≈ 0.5); must be finite and strictly positive
 */
public record EngineConfig(
        ServiceBounds serviceBounds,
        int gridDensityN,
        double maxSearchRadiusMeters,
        OutlierRule outlierRule,
        double epsilonMinutes) {

    public EngineConfig {
        if (serviceBounds == null) {
            throw new IllegalArgumentException("serviceBounds must not be null");
        }
        if (outlierRule == null) {
            throw new IllegalArgumentException("outlierRule must not be null");
        }
        if (gridDensityN < 1) {
            throw new IllegalArgumentException("gridDensityN must be >= 1, was: " + gridDensityN);
        }
        if (!Double.isFinite(maxSearchRadiusMeters) || maxSearchRadiusMeters <= 0.0) {
            throw new IllegalArgumentException(
                    "maxSearchRadiusMeters must be a finite, strictly-positive number, was: "
                            + maxSearchRadiusMeters);
        }
        if (!Double.isFinite(epsilonMinutes) || epsilonMinutes <= 0.0) {
            throw new IllegalArgumentException(
                    "epsilonMinutes must be a finite, strictly-positive number, was: " + epsilonMinutes);
        }
    }
}
