package app.meethalfway.config;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Externalized, city-agnostic engine settings bound from configuration
 * (prefix {@code meethalfway.engine}).
 *
 * <p>These values adapt the engine to a city or environment without changing the
 * optimization logic (Requirements 5.4, 11.5). The 15% efficiency tolerance is
 * deliberately <em>not</em> represented here: Requirement 4.3 mandates it be a
 * fixed domain constant, so it never becomes a configurable field.
 *
 * <p>This is a framework-facing binding record in the {@code config} layer. Later
 * tasks map it into the framework-free domain {@code EngineConfig} at the
 * composition root. Fields are intentionally boxed/nullable so that missing
 * configuration is detectable rather than silently defaulted.
 *
 * @param serviceBoundsMinLat southern latitude bound of the served region
 * @param serviceBoundsMaxLat northern latitude bound of the served region
 * @param serviceBoundsMinLng western longitude bound of the served region
 * @param serviceBoundsMaxLng eastern longitude bound of the served region
 * @param gridDensityN         number of candidate points generated by grid search
 * @param maxSearchRadiusMeters maximum grid extent, in meters
 * @param epsilonMinutes       float-comparison tie tolerance (epsilon), in minutes
 * @param outlierMedianMultipleK the median-multiple {@code k} for the
 *                               {@link app.meethalfway.domain.model.OutlierRule.MedianMultiple}
 *                               rule (Requirement 7.1). Pending calibration with
 *                               real data; a candidate value is {@code 2.0}. When
 *                               absent the composition root applies that default.
 */
@ConfigurationProperties(prefix = "meethalfway.engine")
public record EngineConfigProperties(
        Double serviceBoundsMinLat,
        Double serviceBoundsMaxLat,
        Double serviceBoundsMinLng,
        Double serviceBoundsMaxLng,
        Integer gridDensityN,
        Double maxSearchRadiusMeters,
        Double epsilonMinutes,
        Double outlierMedianMultipleK
) {
}
